### ISSUE TITLE
Shortcut types out "`" character

### ISSUE THREAD

**Issue by iammoen** [sunliangqin/VSCodeQuickNotes#1]
When I toggle quicknotes via the shortcut (Alt + `) the ` character gets typed into whatever file I am in and THEN I am moved over to the notes.txt file. This happens for both my external keyboard as well as my built in keyboard on my laptop. I haven't ever developed an extension for VS Code so I don't know if this is even something that your extension could be at fault for but searching online isn't giving me any clue as to why this might happen so was hoping you might have an idea?

I love the extension by the way. It is note taking exactly the way I was hoping it would be implemented.

I am on a Mac on 10.14 with the following VS Code version.
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**Comment by iammoen** [comment]
Ok so this is not your extension code but the choice of shortcut. But there is something weird that happens when that exact shortcut is used ( Alt + ` ). I changed the shortcut to be ( Alt + tab ) and it works great.

**Comment by sunliangqin** [comment]
Thanks for reporting this issue! I will give it a try to see if I can repro this issue on mac. If so, I will change the default shortcut to Alt+tab on mac.

**Comment by sunliangqin** [comment]
I can repro this issue on mac. I just pushed a new version to change the default keyboard binding on mac to Alt+tab.
